[package]
name = "payments-engine"
version = "0.1.0"
edition = "2021"
authors = ["JB. Griesner <jean.benoit.griesner@gmail.com>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1.6"